spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/vaultvibes
    username: postgres
    password: postgres
  flyway:
    default-schema: public
    schemas: public
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_gqGUV6CKU

cognito:
  user-pool-id: us-east-1_gqGUV6CKU
  client-id: 28lsmakalo98o9p1uv3piho3pq

app:
  frontend-url: http://localhost:5173
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://localhost:3000
      - https://vaultvibes.co.za

